### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by JSav87** [CNugteren/CLBlast#268]
Hi ClBlast group, thanks very much for the great work. I am trying to compile CLBlast.
I have created the Makefile with cmake (3.6.2) and am trying to compile with MinGW 4.9.3 and mingw32-make. The compilation begins and completes until the following error appears:

```
[  9%] Linking CXX executable clblast_tuner_xdot.exe
CMakeFiles\clblast_tuner_xdot.dir/objects.a(xdot.cpp.obj):xdot.cpp:(.text$_ZN7clblast6Kernel11SetArgumentIP7_cl_memEEvjRKT_[__ZN7clblast6Kernel11SetArgumentIP7_cl_memEEvjRKT_]+0x49): undefined reference to `clSetKernelArg@16'
```

followed by a massive list of similar errors until finally:

```
collect2.exe: error: ld returned 1 exit status
CMakeFiles\clblast_tuner_xdot.dir\build.make:111: recipe for target 'clblast_tuner_xdot.exe' failed
mingw32-make[2]: *** [clblast_tuner_xdot.exe] Error 1
```

I have ensured that the OpenCL directory is in my PATH variable. Does anybody have an idea what could be happening?

This is literally the first time I have ever tried to "make" anything, so apologies for any (surely) naiv errors I may have made.

**Comment by JSav87** [comment]
It was a simple linking issue, my mistake, the project compiled fine with mingw32-make. Keep up the good work!
